# Generated by Django 4.1.4 on 2023-03-11 22:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletasks',
            name='task_created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofiletasks',
            name='task_due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 11, 22, 54, 4, 870335, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
