# Generated by Django 4.1.4 on 2023-03-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofiletasks_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiletasks',
            name='task_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
