# Generated by Django 4.1.4 on 2023-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofiletasks_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletasks',
            name='task_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofiletasks',
            name='task_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
